Feature sorting articles
Dimaspb24/DevBlog pull request #10
Opened 2021-12-19 19:22 UTC by aleksey52

2021-12-19 20:20 UTC, antufievsemen requested changes

2021-12-19 20:20 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/ArticleSortingController.java
> +    @GetMapping("/users/{userId}/articles/sorting/{sortingParam}/{sortOrder}")
sorting param и sortOrder вынеси в queryParam( Так как они не учавствуют в запросе напрямую)

2021-12-19 20:20 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/ArticleSortingController.java
> +                                              @NonNull Pageable pageable) {
@DefaultPageable добавь сюда вместо @NonNull

2021-12-19 20:20 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/JwksController.java
> +    public ResponseEntity<Boolean> checkValidateToken(@NonNull @PathVariable String token) {
Token должен быть внутри реквеста а не @PathVariable

2021-12-19 20:20 UTC, antufievsemen commented on src/main/java/com/project/devblog/service/ArticleService.java
> +    public void publish(@NonNull Integer articleId) {
Он используется?

2021-12-19 20:20 UTC, antufievsemen commented on src/main/java/com/project/devblog/service/ArticleService.java
> +                    case ASCENDING: {
Лех этот метод полный пиздец, я думаю есть способы сделать лучше)))

2021-12-20 09:22 UTC, aleksey52 commented on src/main/java/com/project/devblog/service/ArticleService.java
> +    public void publish(@NonNull Integer articleId) {
будет использоваться при публикации статьи, почему бы нет

2021-12-20 10:08 UTC, antufievsemen commented on src/main/java/com/project/devblog/service/ArticleService.java
> +    public void publish(@NonNull Integer articleId) {
У нас есть метод который отвечает за публикацию статьи, зачем нам еще этот метод?

2021-12-20 10:08 UTC, antufievsemen commented on src/main/java/com/project/devblog/service/ArticleService.java
> +    public void publish(@NonNull Integer articleId) {
У нас есть метод который отвечает за публикацию статьи. Этот метод не используется значит он нам не нужен

2021-12-20 14:01 UTC, antufievsemen approved these changes

2021-12-20 14:04 UTC, merged