Create service layer for Article
Dimaspb24/DevBlog pull request #8
Opened 2021-12-16 23:02 UTC by antufievsemen

TagEntity implementet, RatingEntity implementet, CommentEntity implementet, ArticleEntity implementet

2021-12-18 12:28 UTC, Dimaspb24 requested changes

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/request/ArticleRequest.java
> +    @NotNull(message = "Tags must no be null")
Я думал, что добавление тегов не будет являться обязательным параметром для создания статьи.
Как думаешь по этому поводу? Может сделать его @Nullable?

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/UserArticleController.java
> +        return toResponse(articleService.update(userId, articleId, request.getTitle(), request.getTags(),
Я думаю, что метод сервиса должен принимать третьим параметром ArticleRequest request.
1) Так мы уменьшим кол-во параметров
2) Увеличим читаемость
3) При расширении сущности/дто нам не нужно будет менять сигнатуру метода

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/request/CommentRequest.java
> +    @NotBlank(message = "Receiver id is required")
Я думаю здесь этот параметр можно сделать не обязательным и у нас будет более следующая логика:
Если null, тогда сервисный метод сам назначает получателя в виде автора статьи (id статьи мы знаем их запроса)
Если значение есть, то назначаем соответствующего юзера.
Можно сделать это улучшение и потом, но я думаю это не трудно щас исправить.

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/TagController.java
> +    @NonNull
В каком случае здесь в нашей ситуации может оказаться поле в значении null?
Я думаю эта аннотация здесь лишняя...

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/response/CloseArticleResponse.java
> +    private final StatusArticle status;
Я думаю тут стоит сделать тип данных в String, потому что это DTO.

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/response/CloseArticleResponse.java
> +    private final List<TagEntity> tags;
Здесь нужно использовать TagDto вместо TagEntity, чтобы было меньше проблем и полей, а также чтобы не отдавать вид сущности наружу.

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/response/OpenArticleResponse.java
> +    private final List<CommentEntity> comments;
Нужно использовать в списках Dto класс.

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/response/OpenArticleResponse.java
> +    private final List<TagEntity> tags;
Нужно использовать в списках Dto класс.

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/response/OpenArticleResponse.java
> +    private final List<UserArticleEntity> relationUsers;
Нужно использовать в списках Dto класс.

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/response/OpenArticleResponse.java
> +    private final Integer authorId;
Я думаю здесь стоит выводить никнэйм автора статьи для отображения.

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/exceptionhandler/dto/ErrorBody.java
> +public class ErrorBody {
Я думаю здесь можно создать упрощённый конструктор, чтобы не писать лишнего при создании этого класса.

```
    public ErrorBody(@NonNull ErrorsEnum status, @NonNull String message) {
        this.status = status.getStatus().value();
        this.code = status.name();
        this.message = message;
    }

```

2021-12-18 12:28 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/service/ArticleService.java
> +        throw new ArticleConflictException();
Я думаю здесь явно не должно выпадать исключение.

2021-12-18 12:35 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/dto/response/CloseArticleResponse.java
> +    private final StatusArticle status;
Исправил

2021-12-18 12:35 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/dto/request/CommentRequest.java
> +    @NotBlank(message = "Receiver id is required")
Помешает другой логике

2021-12-18 12:35 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/dto/request/ArticleRequest.java
> +    @NotNull(message = "Tags must no be null")
Исправил

2021-12-18 12:36 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/UserArticleController.java
> +        return toResponse(articleService.update(userId, articleId, request.getTitle(), request.getTags(),
Слой сервисов не должен знать о реквестах

2021-12-18 12:37 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/TagController.java
> +    @NonNull
В случае если кто-то забыл реализовать этот класс

2021-12-18 12:48 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/dto/response/OpenArticleResponse.java
> +    private final Integer authorId;
Добавил

2021-12-18 12:48 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/dto/response/OpenArticleResponse.java
> +    private final List<TagEntity> tags;
Исправил

2021-12-18 12:49 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/dto/response/OpenArticleResponse.java
> +    private final List<UserArticleEntity> relationUsers;
Убрал relationsUsers

2021-12-18 12:51 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/exceptionhandler/dto/ErrorBody.java
> +public class ErrorBody {
Исправил

2021-12-18 12:54 UTC, antufievsemen commented on src/main/java/com/project/devblog/service/ArticleService.java
> +        throw new ArticleConflictException();
Исправил логику исключения

2021-12-19 20:09 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/request/ArticleRequest.java
> +    @NotNull(message = "Tags must no be null")
Не исправил

2021-12-19 20:10 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/request/CommentRequest.java
> +    @NotBlank(message = "Receiver id is required")
Какой другой логике это помешает?

2021-12-19 20:14 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/response/OpenArticleResponse.java
> +    private final Integer authorId;
Не добавил

2021-12-19 20:44 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/dto/request/CommentRequest.java
> +    @NotBlank(message = "Receiver id is required")
Мы это обсуждали, этот один реквест на на два метода, тут это поле ничем не мешает и является обязательным

2021-12-19 20:45 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/dto/request/ArticleRequest.java
> +    @NotNull(message = "Tags must no be null")
Ошибся, исправил

2021-12-19 20:46 UTC, antufievsemen commented on src/main/java/com/project/devblog/controller/dto/response/OpenArticleResponse.java
> +    private final Integer authorId;
Ошибка, исправил

2021-12-19 20:58 UTC, Dimaspb24 commented on src/main/java/com/project/devblog/controller/dto/request/CommentRequest.java
> +    @NotBlank(message = "Receiver id is required")
Один реквест на два метода ничем не мешает сделать предложенную мной логику
И это будет довольно аккуратно реализовано, я это уже залил

2021-12-19 22:14 UTC, merged